// Generated by Bisonc++ V4.05.00 on Sat, 12 Mar 2016 13:47:58 +0530

// $insert class.ih
#include "Parser.ih"
#include "ast.cpp"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {300, 1}, // 1: translation_unit ->  struct_specifier
     {300, 1}, // 2: translation_unit ->  function_definition
     {300, 2}, // 3: translation_unit ->  translation_unit function_definition
     {300, 2}, // 4: translation_unit ->  translation_unit struct_specifier
     {301, 6}, // 5: struct_specifier (STRUCT) ->  STRUCT IDENTIFIER '{' declaration_list '}' ';'
     {303, 3}, // 6: function_definition ->  type_specifier fun_declarator compound_statement
     {304, 1}, // 7: type_specifier (VOID) ->  VOID
     {304, 1}, // 8: type_specifier (INT) ->  INT
     {304, 1}, // 9: type_specifier (FLOAT) ->  FLOAT
     {304, 2}, // 10: type_specifier (STRUCT) ->  STRUCT IDENTIFIER
     {305, 4}, // 11: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' parameter_list ')'
     {305, 3}, // 12: fun_declarator (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {305, 2}, // 13: fun_declarator ('*') ->  '*' fun_declarator
     {306, 1}, // 14: parameter_list ->  parameter_declaration
     {306, 3}, // 15: parameter_list (',') ->  parameter_list ',' parameter_declaration
     {307, 2}, // 16: parameter_declaration ->  type_specifier declarator
     {308, 1}, // 17: declarator (IDENTIFIER) ->  IDENTIFIER
     {308, 4}, // 18: declarator ('[') ->  declarator '[' primary_expression ']'
     {308, 2}, // 19: declarator ('*') ->  '*' declarator
     {309, 1}, // 20: primary_expression (IDENTIFIER) ->  IDENTIFIER
     {309, 1}, // 21: primary_expression (INT_CONSTANT) ->  INT_CONSTANT
     {309, 1}, // 22: primary_expression (FLOAT_CONSTANT) ->  FLOAT_CONSTANT
     {309, 1}, // 23: primary_expression (STRING_LITERAL) ->  STRING_LITERAL
     {309, 3}, // 24: primary_expression ('(') ->  '(' expression ')'
     {310, 2}, // 25: compound_statement ('{') ->  '{' '}'
     {310, 3}, // 26: compound_statement ('{') ->  '{' statement_list '}'
     {310, 4}, // 27: compound_statement ('{') ->  '{' declaration_list statement_list '}'
     {311, 1}, // 28: statement_list ->  statement
     {311, 2}, // 29: statement_list ->  statement_list statement
     {312, 3}, // 30: statement ('{') ->  '{' statement_list '}'
     {312, 1}, // 31: statement ->  selection_statement
     {312, 1}, // 32: statement ->  iteration_statement
     {312, 1}, // 33: statement ->  assignment_statement
     {312, 3}, // 34: statement (RETURN) ->  RETURN expression ';'
     {313, 1}, // 35: assignment_statement (';') ->  ';'
     {313, 2}, // 36: assignment_statement (';') ->  expression ';'
     {314, 1}, // 37: expression ->  logical_or_expression
     {314, 3}, // 38: expression ('=') ->  unary_expression '=' expression
     {315, 1}, // 39: logical_or_expression ->  logical_and_expression
     {315, 3}, // 40: logical_or_expression (OR_OP) ->  logical_or_expression OR_OP logical_and_expression
     {316, 1}, // 41: logical_and_expression ->  equality_expression
     {316, 3}, // 42: logical_and_expression (AND_OP) ->  logical_and_expression AND_OP equality_expression
     {317, 1}, // 43: equality_expression ->  relational_expression
     {317, 3}, // 44: equality_expression (EQ_OP) ->  equality_expression EQ_OP relational_expression
     {317, 3}, // 45: equality_expression (NE_OP) ->  equality_expression NE_OP relational_expression
     {318, 1}, // 46: relational_expression ->  additive_expression
     {318, 3}, // 47: relational_expression ('<') ->  relational_expression '<' additive_expression
     {318, 3}, // 48: relational_expression ('>') ->  relational_expression '>' additive_expression
     {318, 3}, // 49: relational_expression (LE_OP) ->  relational_expression LE_OP additive_expression
     {318, 3}, // 50: relational_expression (GE_OP) ->  relational_expression GE_OP additive_expression
     {319, 1}, // 51: additive_expression ->  multiplicative_expression
     {319, 3}, // 52: additive_expression ('+') ->  additive_expression '+' multiplicative_expression
     {319, 3}, // 53: additive_expression ('-') ->  additive_expression '-' multiplicative_expression
     {320, 1}, // 54: multiplicative_expression ->  unary_expression
     {320, 3}, // 55: multiplicative_expression ('*') ->  multiplicative_expression '*' unary_expression
     {320, 3}, // 56: multiplicative_expression ('/') ->  multiplicative_expression '/' unary_expression
     {321, 1}, // 57: unary_expression ->  postfix_expression
     {321, 2}, // 58: unary_expression ->  unary_operator unary_expression
     {322, 1}, // 59: postfix_expression ->  primary_expression
     {322, 3}, // 60: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' ')'
     {322, 4}, // 61: postfix_expression (IDENTIFIER) ->  IDENTIFIER '(' expression_list ')'
     {322, 4}, // 62: postfix_expression ('[') ->  postfix_expression '[' expression ']'
     {322, 3}, // 63: postfix_expression ('.') ->  postfix_expression '.' IDENTIFIER
     {322, 3}, // 64: postfix_expression (PTR_OP) ->  postfix_expression PTR_OP IDENTIFIER
     {322, 2}, // 65: postfix_expression (INC_OP) ->  postfix_expression INC_OP
     {323, 1}, // 66: expression_list ->  expression
     {323, 3}, // 67: expression_list (',') ->  expression_list ',' expression
     {324, 1}, // 68: unary_operator ('-') ->  '-'
     {324, 1}, // 69: unary_operator ('!') ->  '!'
     {324, 1}, // 70: unary_operator ('&') ->  '&'
     {324, 1}, // 71: unary_operator ('*') ->  '*'
     {325, 7}, // 72: selection_statement (IF) ->  IF '(' expression ')' statement ELSE statement
     {326, 5}, // 73: iteration_statement (WHILE) ->  WHILE '(' expression ')' statement
     {326, 9}, // 74: iteration_statement (FOR) ->  FOR '(' expression ';' expression ';' expression ')' statement
     {302, 1}, // 75: declaration_list ->  declaration
     {302, 2}, // 76: declaration_list ->  declaration_list declaration
     {327, 3}, // 77: declaration (';') ->  type_specifier declarator_list ';'
     {328, 1}, // 78: declarator_list ->  declarator
     {328, 3}, // 79: declarator_list (',') ->  declarator_list ',' declarator
     {329, 1}, // 80: translation_unit_$ ->  translation_unit
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 9} },                       
    { {       300}, { 1} }, // translation_unit   
    { {       301}, { 2} }, // struct_specifier   
    { {       303}, { 3} }, // function_definition
    { {       257}, { 4} }, // STRUCT             
    { {       304}, { 5} }, // type_specifier     
    { {       258}, { 6} }, // VOID               
    { {       259}, { 7} }, // INT                
    { {       260}, { 8} }, // FLOAT              
    { {         0}, { 0} },                       
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            9} },                       
    { {       303}, {            9} }, // function_definition
    { {       301}, {           10} }, // struct_specifier   
    { {       304}, {            5} }, // type_specifier     
    { {       257}, {            4} }, // STRUCT             
    { {       258}, {            6} }, // VOID               
    { {       259}, {            7} }, // INT                
    { {       260}, {            8} }, // FLOAT              
    { {     _EOF_}, { PARSE_ACCEPT} },                       
    { {         0}, {            0} },                       
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       277}, { 11} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  4} },                  
    { {       305}, { 12} }, // fun_declarator
    { {       277}, { 13} }, // IDENTIFIER    
    { {        42}, { 14} }, // '*'           
    { {         0}, {  0} },                  
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_11[] =
{
    { { REQ_DEF}, {   2} },       
    { {     123}, {  15} }, // '{'
    { {       0}, { -10} },       
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  3} },                      
    { {       310}, { 16} }, // compound_statement
    { {       123}, { 17} }, // '{'               
    { {         0}, {  0} },                      
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 18} }, // '('
    { {         0}, {  0} },       
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  4} },                  
    { {       305}, { 19} }, // fun_declarator
    { {       277}, { 13} }, // IDENTIFIER    
    { {        42}, { 14} }, // '*'           
    { {         0}, {  0} },                  
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  8} },                    
    { {       302}, { 20} }, // declaration_list
    { {       327}, { 21} }, // declaration     
    { {       304}, { 22} }, // type_specifier  
    { {       258}, {  6} }, // VOID            
    { {       259}, {  7} }, // INT             
    { {       260}, {  8} }, // FLOAT           
    { {       257}, { 23} }, // STRUCT          
    { {         0}, {  0} },                    
};

SR__ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, { 40} },                             
    { {       125}, { 24} }, // '}'                      
    { {       311}, { 25} }, // statement_list           
    { {       302}, { 26} }, // declaration_list         
    { {       312}, { 27} }, // statement                
    { {       327}, { 21} }, // declaration              
    { {       123}, { 28} }, // '{'                      
    { {       325}, { 29} }, // selection_statement      
    { {       326}, { 30} }, // iteration_statement      
    { {       313}, { 31} }, // assignment_statement     
    { {       261}, { 32} }, // RETURN                   
    { {       304}, { 22} }, // type_specifier           
    { {       273}, { 33} }, // IF                       
    { {       275}, { 34} }, // WHILE                    
    { {       276}, { 35} }, // FOR                      
    { {        59}, { 36} }, // ';'                      
    { {       314}, { 37} }, // expression               
    { {       258}, {  6} }, // VOID                     
    { {       259}, {  7} }, // INT                      
    { {       260}, {  8} }, // FLOAT                    
    { {       257}, { 23} }, // STRUCT                   
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  9} },                         
    { {       306}, { 57} }, // parameter_list       
    { {        41}, { 58} }, // ')'                  
    { {       307}, { 59} }, // parameter_declaration
    { {       304}, { 60} }, // type_specifier       
    { {       258}, {  6} }, // VOID                 
    { {       259}, {  7} }, // INT                  
    { {       260}, {  8} }, // FLOAT                
    { {       257}, { 23} }, // STRUCT               
    { {         0}, {  0} },                         
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  8} },                  
    { {       125}, { 61} }, // '}'           
    { {       327}, { 62} }, // declaration   
    { {       304}, { 22} }, // type_specifier
    { {       258}, {  6} }, // VOID          
    { {       259}, {  7} }, // INT           
    { {       260}, {  8} }, // FLOAT         
    { {       257}, { 23} }, // STRUCT        
    { {         0}, {  0} },                  
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -75} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  5} },                   
    { {       328}, { 63} }, // declarator_list
    { {       308}, { 64} }, // declarator     
    { {       277}, { 65} }, // IDENTIFIER     
    { {        42}, { 66} }, // '*'            
    { {         0}, {  0} },                   
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       277}, { 67} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 32} },                             
    { {       125}, { 68} }, // '}'                      
    { {       312}, { 69} }, // statement                
    { {       123}, { 28} }, // '{'                      
    { {       325}, { 29} }, // selection_statement      
    { {       326}, { 30} }, // iteration_statement      
    { {       313}, { 31} }, // assignment_statement     
    { {       261}, { 32} }, // RETURN                   
    { {       273}, { 33} }, // IF                       
    { {       275}, { 34} }, // WHILE                    
    { {       276}, { 35} }, // FOR                      
    { {        59}, { 36} }, // ';'                      
    { {       314}, { 37} }, // expression               
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 38} },                             
    { {       311}, { 70} }, // statement_list           
    { {       327}, { 62} }, // declaration              
    { {       312}, { 27} }, // statement                
    { {       304}, { 22} }, // type_specifier           
    { {       123}, { 28} }, // '{'                      
    { {       325}, { 29} }, // selection_statement      
    { {       326}, { 30} }, // iteration_statement      
    { {       313}, { 31} }, // assignment_statement     
    { {       261}, { 32} }, // RETURN                   
    { {       258}, {  6} }, // VOID                     
    { {       259}, {  7} }, // INT                      
    { {       260}, {  8} }, // FLOAT                    
    { {       257}, { 23} }, // STRUCT                   
    { {       273}, { 33} }, // IF                       
    { {       275}, { 34} }, // WHILE                    
    { {       276}, { 35} }, // FOR                      
    { {        59}, { 36} }, // ';'                      
    { {       314}, { 37} }, // expression               
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 32} },                             
    { {       311}, { 71} }, // statement_list           
    { {       312}, { 27} }, // statement                
    { {       123}, { 28} }, // '{'                      
    { {       325}, { 29} }, // selection_statement      
    { {       326}, { 30} }, // iteration_statement      
    { {       313}, { 31} }, // assignment_statement     
    { {       261}, { 32} }, // RETURN                   
    { {       273}, { 33} }, // IF                       
    { {       275}, { 34} }, // WHILE                    
    { {       276}, { 35} }, // FOR                      
    { {        59}, { 36} }, // ';'                      
    { {       314}, { 37} }, // expression               
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 21} },                             
    { {       314}, { 72} }, // expression               
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 73} }, // '('
    { {         0}, {  0} },       
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 74} }, // '('
    { {         0}, {  0} },       
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 75} }, // '('
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 76} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_DEF}, {   2} },         
    { {     265}, {  77} }, // OR_OP
    { {       0}, { -37} },         
};

SR__ s_39[] =
{
    { { REQ_DEF}, {   2} },       
    { {      61}, {  78} }, // '='
    { {       0}, { -54} },       
};

SR__ s_40[] =
{
    { { REQ_DEF}, {   2} },          
    { {     266}, {  79} }, // AND_OP
    { {       0}, { -39} },          
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   5} },          
    { {      91}, {  80} }, // '['   
    { {      46}, {  81} }, // '.'   
    { {     272}, {  82} }, // PTR_OP
    { {     271}, {  83} }, // INC_OP
    { {       0}, { -57} },          
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 14} },                      
    { {       321}, { 84} }, // unary_expression  
    { {       322}, { 41} }, // postfix_expression
    { {       324}, { 42} }, // unary_operator    
    { {       309}, { 44} }, // primary_expression
    { {       277}, { 45} }, // IDENTIFIER        
    { {        45}, { 46} }, // '-'               
    { {        33}, { 47} }, // '!'               
    { {        38}, { 48} }, // '&'               
    { {        42}, { 49} }, // '*'               
    { {       262}, { 51} }, // INT_CONSTANT      
    { {       263}, { 52} }, // FLOAT_CONSTANT    
    { {       264}, { 53} }, // STRING_LITERAL    
    { {        40}, { 54} }, // '('               
    { {         0}, {  0} },                      
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   3} },         
    { {     267}, {  85} }, // EQ_OP
    { {     268}, {  86} }, // NE_OP
    { {       0}, { -41} },         
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -59} }, 
};

SR__ s_45[] =
{
    { { REQ_DEF}, {   2} },       
    { {      40}, {  87} }, // '('
    { {       0}, { -20} },       
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -68} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -69} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -70} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -71} }, 
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  88} }, // '<'  
    { {      62}, {  89} }, // '>'  
    { {     269}, {  90} }, // LE_OP
    { {     270}, {  91} }, // GE_OP
    { {       0}, { -43} },         
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 21} },                             
    { {       314}, { 92} }, // expression               
    { {       315}, { 38} }, // logical_or_expression    
    { {       321}, { 39} }, // unary_expression         
    { {       316}, { 40} }, // logical_and_expression   
    { {       322}, { 41} }, // postfix_expression       
    { {       324}, { 42} }, // unary_operator           
    { {       317}, { 43} }, // equality_expression      
    { {       309}, { 44} }, // primary_expression       
    { {       277}, { 45} }, // IDENTIFIER               
    { {        45}, { 46} }, // '-'                      
    { {        33}, { 47} }, // '!'                      
    { {        38}, { 48} }, // '&'                      
    { {        42}, { 49} }, // '*'                      
    { {       318}, { 50} }, // relational_expression    
    { {       262}, { 51} }, // INT_CONSTANT             
    { {       263}, { 52} }, // FLOAT_CONSTANT           
    { {       264}, { 53} }, // STRING_LITERAL           
    { {        40}, { 54} }, // '('                      
    { {       319}, { 55} }, // additive_expression      
    { {       320}, { 56} }, // multiplicative_expression
    { {         0}, {  0} },                             
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  93} }, // '+'
    { {      45}, {  94} }, // '-'
    { {       0}, { -46} },       
};

SR__ s_56[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  95} }, // '*'
    { {      47}, {  96} }, // '/'
    { {       0}, { -51} },       
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  3} },       
    { {        41}, { 97} }, // ')'
    { {        44}, { 98} }, // ','
    { {         0}, {  0} },       
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       308}, { 99} }, // declarator
    { {       277}, { 65} }, // IDENTIFIER
    { {        42}, { 66} }, // '*'       
    { {         0}, {  0} },              
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 100} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -76} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        59}, { 101} }, // ';'
    { {        44}, { 102} }, // ','
    { {         0}, {   0} },       
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, { 103} }, // '['
    { {       0}, { -78} },       
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {   4} },              
    { {       308}, { 104} }, // declarator
    { {       277}, {  65} }, // IDENTIFIER
    { {        42}, {  66} }, // '*'       
    { {         0}, {   0} },              
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  32} },                             
    { {       125}, { 105} }, // '}'                      
    { {       312}, {  69} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  32} },                             
    { {       125}, { 106} }, // '}'                      
    { {       312}, {  69} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 107} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 108} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 109} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 110} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  19} },                             
    { {       316}, { 111} }, // logical_and_expression   
    { {       317}, {  43} }, // equality_expression      
    { {       318}, {  50} }, // relational_expression    
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 113} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  18} },                             
    { {       317}, { 114} }, // equality_expression      
    { {       318}, {  50} }, // relational_expression    
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 115} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       277}, { 116} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       277}, { 117} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -65} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  17} },                             
    { {       318}, { 118} }, // relational_expression    
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  17} },                             
    { {       318}, { 119} }, // relational_expression    
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  23} },                             
    { {        41}, { 120} }, // ')'                      
    { {       323}, { 121} }, // expression_list          
    { {       314}, { 122} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 123} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 124} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 125} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {  16} },                             
    { {       319}, { 126} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 127} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 128} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {  15} },                             
    { {       320}, { 129} }, // multiplicative_expression
    { {       321}, { 112} }, // unary_expression         
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {         0}, {   0} },                             
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {  14} },                      
    { {       321}, { 130} }, // unary_expression  
    { {       322}, {  41} }, // postfix_expression
    { {       324}, {  42} }, // unary_operator    
    { {       309}, {  44} }, // primary_expression
    { {       277}, {  45} }, // IDENTIFIER        
    { {        45}, {  46} }, // '-'               
    { {        33}, {  47} }, // '!'               
    { {        38}, {  48} }, // '&'               
    { {        42}, {  49} }, // '*'               
    { {       262}, {  51} }, // INT_CONSTANT      
    { {       263}, {  52} }, // FLOAT_CONSTANT    
    { {       264}, {  53} }, // STRING_LITERAL    
    { {        40}, {  54} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {  14} },                      
    { {       321}, { 131} }, // unary_expression  
    { {       322}, {  41} }, // postfix_expression
    { {       324}, {  42} }, // unary_operator    
    { {       309}, {  44} }, // primary_expression
    { {       277}, {  45} }, // IDENTIFIER        
    { {        45}, {  46} }, // '-'               
    { {        33}, {  47} }, // '!'               
    { {        38}, {  48} }, // '&'               
    { {        42}, {  49} }, // '*'               
    { {       262}, {  51} }, // INT_CONSTANT      
    { {       263}, {  52} }, // FLOAT_CONSTANT    
    { {       264}, {  53} }, // STRING_LITERAL    
    { {        40}, {  54} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {   7} },                         
    { {       307}, { 132} }, // parameter_declaration
    { {       304}, {  60} }, // type_specifier       
    { {       258}, {   6} }, // VOID                 
    { {       259}, {   7} }, // INT                  
    { {       260}, {   8} }, // FLOAT                
    { {       257}, {  23} }, // STRUCT               
    { {         0}, {   0} },                         
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, { 103} }, // '['
    { {       0}, { -16} },       
};

SR__ s_100[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -77} }, 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   4} },              
    { {       308}, { 133} }, // declarator
    { {       277}, {  65} }, // IDENTIFIER
    { {        42}, {  66} }, // '*'       
    { {         0}, {   0} },              
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   7} },                      
    { {       309}, { 134} }, // primary_expression
    { {       277}, { 135} }, // IDENTIFIER        
    { {       262}, {  51} }, // INT_CONSTANT      
    { {       263}, {  52} }, // FLOAT_CONSTANT    
    { {       264}, {  53} }, // STRING_LITERAL    
    { {        40}, {  54} }, // '('               
    { {         0}, {   0} },                      
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, { 103} }, // '['
    { {       0}, { -19} },       
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 136} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_109[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 137} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 138} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_111[] =
{
    { { REQ_DEF}, {   2} },          
    { {     266}, {  79} }, // AND_OP
    { {       0}, { -40} },          
};

SR__ s_112[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_113[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_114[] =
{
    { { REQ_DEF}, {   3} },         
    { {     267}, {  85} }, // EQ_OP
    { {     268}, {  86} }, // NE_OP
    { {       0}, { -42} },         
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 139} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_116[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -63} }, 
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -64} }, 
};

SR__ s_118[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  88} }, // '<'  
    { {      62}, {  89} }, // '>'  
    { {     269}, {  90} }, // LE_OP
    { {     270}, {  91} }, // GE_OP
    { {       0}, { -44} },         
};

SR__ s_119[] =
{
    { { REQ_DEF}, {   5} },         
    { {      60}, {  88} }, // '<'  
    { {      62}, {  89} }, // '>'  
    { {     269}, {  90} }, // LE_OP
    { {     270}, {  91} }, // GE_OP
    { {       0}, { -45} },         
};

SR__ s_120[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_121[] =
{
    { { REQ_TOKEN}, {   3} },       
    { {        41}, { 140} }, // ')'
    { {        44}, { 141} }, // ','
    { {         0}, {   0} },       
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -66} }, 
};

SR__ s_123[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  93} }, // '+'
    { {      45}, {  94} }, // '-'
    { {       0}, { -47} },       
};

SR__ s_124[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  93} }, // '+'
    { {      45}, {  94} }, // '-'
    { {       0}, { -48} },       
};

SR__ s_125[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  93} }, // '+'
    { {      45}, {  94} }, // '-'
    { {       0}, { -49} },       
};

SR__ s_126[] =
{
    { { REQ_DEF}, {   3} },       
    { {      43}, {  93} }, // '+'
    { {      45}, {  94} }, // '-'
    { {       0}, { -50} },       
};

SR__ s_127[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_128[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  95} }, // '*'
    { {      47}, {  96} }, // '/'
    { {       0}, { -52} },       
};

SR__ s_129[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  95} }, // '*'
    { {      47}, {  96} }, // '/'
    { {       0}, { -53} },       
};

SR__ s_130[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_131[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_132[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_133[] =
{
    { { REQ_DEF}, {   2} },       
    { {      91}, { 103} }, // '['
    { {       0}, { -79} },       
};

SR__ s_134[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        93}, { 142} }, // ']'
    { {         0}, {   0} },       
};

SR__ s_135[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_136[] =
{
    { { REQ_TOKEN}, {  31} },                             
    { {       312}, { 143} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_137[] =
{
    { { REQ_TOKEN}, {  31} },                             
    { {       312}, { 144} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_138[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 145} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_139[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_140[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_141[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 146} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_142[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_143[] =
{
    { { REQ_TOKEN}, {   2} },        
    { {       274}, { 147} }, // ELSE
    { {         0}, {   0} },        
};

SR__ s_144[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -73} }, 
};

SR__ s_145[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 148} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_146[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -67} }, 
};

SR__ s_147[] =
{
    { { REQ_TOKEN}, {  31} },                             
    { {       312}, { 149} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_148[] =
{
    { { REQ_TOKEN}, {  21} },                             
    { {       314}, { 150} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_149[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -72} }, 
};

SR__ s_150[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        41}, { 151} }, // ')'
    { {         0}, {   0} },       
};

SR__ s_151[] =
{
    { { REQ_TOKEN}, {  31} },                             
    { {       312}, { 152} }, // statement                
    { {       123}, {  28} }, // '{'                      
    { {       325}, {  29} }, // selection_statement      
    { {       326}, {  30} }, // iteration_statement      
    { {       313}, {  31} }, // assignment_statement     
    { {       261}, {  32} }, // RETURN                   
    { {       273}, {  33} }, // IF                       
    { {       275}, {  34} }, // WHILE                    
    { {       276}, {  35} }, // FOR                      
    { {        59}, {  36} }, // ';'                      
    { {       314}, {  37} }, // expression               
    { {       315}, {  38} }, // logical_or_expression    
    { {       321}, {  39} }, // unary_expression         
    { {       316}, {  40} }, // logical_and_expression   
    { {       322}, {  41} }, // postfix_expression       
    { {       324}, {  42} }, // unary_operator           
    { {       317}, {  43} }, // equality_expression      
    { {       309}, {  44} }, // primary_expression       
    { {       277}, {  45} }, // IDENTIFIER               
    { {        45}, {  46} }, // '-'                      
    { {        33}, {  47} }, // '!'                      
    { {        38}, {  48} }, // '&'                      
    { {        42}, {  49} }, // '*'                      
    { {       318}, {  50} }, // relational_expression    
    { {       262}, {  51} }, // INT_CONSTANT             
    { {       263}, {  52} }, // FLOAT_CONSTANT           
    { {       264}, {  53} }, // STRING_LITERAL           
    { {        40}, {  54} }, // '('                      
    { {       319}, {  55} }, // additive_expression      
    { {       320}, {  56} }, // multiplicative_expression
    { {         0}, {   0} },                             
};

SR__ s_152[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -74} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,  s_125,  s_126,  s_127,  s_128,  s_129,
  s_130,  s_131,  s_132,  s_133,  s_134,  s_135,  s_136,  s_137,  s_138,  s_139,
  s_140,  s_141,  s_142,  s_143,  s_144,  s_145,  s_146,  s_147,  s_148,  s_149,
  s_150,  s_151,  s_152,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


Meta__::SType ParserBase::d_val__; 
void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 6:
#line 33 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[0].data<Tag__::StmtAst>();
         d_val__.get<Tag__::StmtAst>()->print();
         }
        break;

        case 20:
#line 70 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Identifier(d_vsp__[0].data<Tag__::String>());
         }
        break;

        case 21:
#line 73 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new IntConst(d_vsp__[0].data<Tag__::Int>());
         }
        break;

        case 22:
#line 76 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new FloatConst(d_vsp__[0].data<Tag__::Float>());
         }
        break;

        case 23:
#line 79 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new StringConst(d_vsp__[0].data<Tag__::String>());
         }
        break;

        case 24:
#line 82 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[-1].data<Tag__::ExpAst>();
         }
        break;

        case 25:
#line 88 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new BlockStmt();
         }
        break;

        case 26:
#line 91 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[-1].data<Tag__::StmtAst>();
         }
        break;

        case 27:
#line 95 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[-1].data<Tag__::StmtAst>();
         }
        break;

        case 28:
#line 101 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new BlockStmt(d_vsp__[0].data<Tag__::StmtAst>());
         }
        break;

        case 29:
#line 104 "parse.y"
        {
         ((BlockStmt*)d_vsp__[-1].data<Tag__::StmtAst>())->children.push_back(d_vsp__[0].data<Tag__::StmtAst>());
         d_val__.get<Tag__::StmtAst>() = d_vsp__[-1].data<Tag__::StmtAst>();
         }
        break;

        case 30:
#line 111 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[-1].data<Tag__::StmtAst>();
         }
        break;

        case 31:
#line 114 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[0].data<Tag__::StmtAst>();
         }
        break;

        case 32:
#line 117 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[0].data<Tag__::StmtAst>();
         }
        break;

        case 33:
#line 120 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = d_vsp__[0].data<Tag__::StmtAst>();
         }
        break;

        case 34:
#line 123 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new Return(d_vsp__[-1].data<Tag__::ExpAst>());
         }
        break;

        case 35:
#line 129 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new Ass();
         }
        break;

        case 36:
#line 132 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new Ass(d_vsp__[-1].data<Tag__::ExpAst>());
         }
        break;

        case 37:
#line 138 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 38:
#line 141 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Assign(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>());
         }
        break;

        case 39:
#line 148 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 40:
#line 151 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::OR);
         }
        break;

        case 41:
#line 156 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 42:
#line 159 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::AND);
         }
        break;

        case 43:
#line 165 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 44:
#line 168 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::EQ_OP);
         }
        break;

        case 45:
#line 171 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::NE_OP);
         }
        break;

        case 46:
#line 176 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 47:
#line 179 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::LT);
         }
        break;

        case 48:
#line 182 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::GT);
         }
        break;

        case 49:
#line 185 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::LE_OP);
         }
        break;

        case 50:
#line 188 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::GE_OP);
         }
        break;

        case 51:
#line 194 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 52:
#line 197 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::PLUS);
         }
        break;

        case 53:
#line 200 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::MINUS);
         }
        break;

        case 54:
#line 206 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 55:
#line 209 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::MULT);
         }
        break;

        case 56:
#line 212 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpBinary(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::ExpAst>(), opNameB::MULT);
         }
        break;

        case 57:
#line 217 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 58:
#line 220 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(d_vsp__[0].data<Tag__::ExpAst>(), (OpUnary*)d_vsp__[-1].data<Tag__::ExpAst>());
         }
        break;

        case 59:
#line 226 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = d_vsp__[0].data<Tag__::ExpAst>();
         }
        break;

        case 60:
#line 229 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Funcall(new Identifier(d_vsp__[-2].data<Tag__::String>()));
         }
        break;

        case 61:
#line 232 "parse.y"
        {
         ((Funcall*)d_vsp__[-1].data<Tag__::ExpAst>())->children.insert(((Funcall*)d_vsp__[-1].data<Tag__::ExpAst>())->children.begin(), new Identifier(d_vsp__[-3].data<Tag__::String>()));
         d_val__.get<Tag__::ExpAst>() = d_vsp__[-1].data<Tag__::ExpAst>();
         }
        break;

        case 62:
#line 236 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new ArrayRef(d_vsp__[-3].data<Tag__::ExpAst>(), d_vsp__[-1].data<Tag__::ExpAst>());
         }
        break;

        case 63:
#line 239 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Member(d_vsp__[-2].data<Tag__::ExpAst>(), new Identifier(d_vsp__[0].data<Tag__::String>()));
         }
        break;

        case 64:
#line 242 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Arrow(d_vsp__[-2].data<Tag__::ExpAst>(), new Identifier(d_vsp__[0].data<Tag__::String>()));
         }
        break;

        case 65:
#line 245 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(d_vsp__[-1].data<Tag__::ExpAst>(), opNameU::PP);
         }
        break;

        case 66:
#line 253 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new Funcall(d_vsp__[0].data<Tag__::ExpAst>());
         }
        break;

        case 67:
#line 256 "parse.y"
        {
         ((Funcall*)d_vsp__[-2].data<Tag__::ExpAst>())->children.push_back(d_vsp__[0].data<Tag__::ExpAst>());
         d_val__.get<Tag__::ExpAst>() = d_vsp__[-2].data<Tag__::ExpAst>();
         }
        break;

        case 68:
#line 263 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(opNameU::UMINUS);
         }
        break;

        case 69:
#line 266 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(opNameU::NOT);
         }
        break;

        case 70:
#line 269 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(opNameU::DEREF);
         }
        break;

        case 71:
#line 272 "parse.y"
        {
         d_val__.get<Tag__::ExpAst>() = new OpUnary(opNameU::POINTER);
         }
        break;

        case 72:
#line 278 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new If(d_vsp__[-4].data<Tag__::ExpAst>(), d_vsp__[-2].data<Tag__::StmtAst>(), d_vsp__[0].data<Tag__::StmtAst>());
         }
        break;

        case 73:
#line 284 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new While(d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::StmtAst>());
         }
        break;

        case 74:
#line 287 "parse.y"
        {
         d_val__.get<Tag__::StmtAst>() = new For(d_vsp__[-6].data<Tag__::ExpAst>(), d_vsp__[-4].data<Tag__::ExpAst>(), d_vsp__[-2].data<Tag__::ExpAst>(), d_vsp__[0].data<Tag__::StmtAst>());
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
    // $insert threading
    SR__ *sr = s_state[d_state__];        // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;        // sentinel-index in the SR__ array

    SR__ *lastElementPtr = sr + lastIdx;
    SR__ *elementPtr = sr + 1;            // start the search at s_xx[1]

    lastElementPtr->d_token = d_token__;// set search-token

    while (elementPtr->d_token != d_token__)
        ++elementPtr;

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}

// $insert polymorphicImpl
namespace Meta__
{
   Base::~Base()
   {}
}




